// Generated by tools/photos.py. Don't edit by hand; re-run the script instead.
window.PHOTOS = [
  {
    "src": "full/r26-k400-07.jpg",
    "w": 4907,
    "h": 3254,
    "bytes": 21512321,
    "date": "2025-12-03T08:54:49",
    "sizes": [
      {
        "w": 800,
        "src": "sizes/r26-k400-07-800.jpg"
      },
      {
        "w": 1600,
        "src": "sizes/r26-k400-07-1600.jpg"
      },
      {
        "w": 2400,
        "src": "sizes/r26-k400-07-2400.jpg"
      },
      {
        "w": 3600,
        "src": "sizes/r26-k400-07-3600.jpg"
      }
    ]
  },
  {
    "src": "full/r27-e100-13.jpg",
    "w": 6774,
    "h": 4492,
    "bytes": 38744301,
    "date": "2025-12-03T08:20:49",
    "sizes": [
      {
        "w": 800,
        "src": "sizes/r27-e100-13-800.jpg"
      },
      {
        "w": 1600,
        "src": "sizes/r27-e100-13-1600.jpg"
      },
      {
        "w": 2400,
        "src": "sizes/r27-e100-13-2400.jpg"
      },
      {
        "w": 3600,
        "src": "sizes/r27-e100-13-3600.jpg"
      }
    ]
  }
];
